### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/AUX_PSU#4]
- [x] NMOS won't work for a negative rail. Use PMOS + level shifters
- [x] add DC connector (the same as in Thermostat) on the rear edge to not force users to waste EEM slot
- [x] add LC filter between SMPS and LDO, they have not sufficient PSRR for switching frequency
- [x] resistors at the decoder outputs are not needed
- [x] rotate all strings, so the user doesn't need to set the Altium option that does it. 
- [x] connect remaining ADC inputs to dividers measuring LDO outputs
- [x] add notes explaining current linit values and LED thresholds
- [x] Front panel LEDs need at least 1mA of current. Use same front panel LEDs current as other designs using same PNs. 
- [x] are U sure the negative LDO produces positive ADC_Imon signal?
- [x] now the inactive switch positions result with max output voltages
- [x] use 8-position switches like[ this one](https://www.digikey.com/product-detail/en/S-8011/563-1054-ND/948365?utm_campaign=buynow&utm_medium=aggregator&curr=usd&utm_source=octopart). There is 3D model in Digikey.
- [x] assign all 8 positions, 3V and 6V is often needed. The rest of them must give known value. Place 0R resistors so the user can assign needed value.
- [x] add version with knob or some handle to the BOM. Vendors usually have such accessories, so the user has a choice. Changing the switch settings using a screwdriver will break the switch slot quickly.
- [x] alternatively, one can use [standard](https://pl.mouser.com/ProductDetail/NKK-Switches/NR01105ANG13-2A?qs=EU6FO9ffTwcM3pHNV2SdFA%3D%3D) 1:6 switch, but it would need a tiny RA adapter - a piece of PCB and RA 2.54 connector. But they are nearly 10$ per piece. However, they would last longer.
- [x] apply A3 template with WUT logo
- [x] connect all 3 connectors in the same manner. Place them on the top sheet. They will fit
![obraz](https://user-images.githubusercontent.com/4325054/94346339-4cae8980-002c-11eb-9239-5c155181784f.png)

**Comment by gkasprow** [comment]
@dtcallcock @jbqubit @hartytp can you have a look at the schematics?
@michalgaska please place a PDF version to make review easier.

**Comment by dtcallcock** [comment]
Any joy on the pdf?

**Comment by jbqubit** [comment]
What's the status of this board? Searching for a schematic PDF still brings more tears than joy.

**Comment by gkasprow** [comment]
@jbqubit here is the schematic. The output connector signal assignment will change.
[Aux_PSU.PDF](https://github.com/sinara-hw/AUX_PSU/files/6052347/Aux_PSU.PDF)

**Comment by gkasprow** [comment]
It goes to production together with SHuttler boards

**Comment by michalgaska** [comment]
I committed the current design files. 
Schematic: 
[AuxPowerSupply.pdf](https://github.com/sinara-hw/AUX_PSU/files/6053862/AuxPowerSupply.pdf)

**Comment by dtcallcock** [comment]
- It's a bit odd one of the OC LEDs is green, not red.  I guess it would add a BOM line though.

<img width="174" alt="image" src="https://user-images.githubusercontent.com/20587606/110068573-d88ab700-7d2a-11eb-8b24-91bf7d7ba90e.png">

- I think it'd be much more useful to have all 3 voltages plus ground on each output connector instead of one voltage on each connector.

- The rear power connector is barrel right now.  I thought the Molex type was the preferred population option for internal power connectors though.

**Comment by gkasprow** [comment]
> I think it'd be much more useful to have all 3 voltages plus ground on each output connector instead of one voltage on each connector. 
>The rear power connector is barrel right now. I thought the Molex type was the preferred population option for internal power connectors though.
>It's a bit odd one of the OC LEDs is green, not red. I guess it would add a BOM line though.

are you looking at the right schematic? This was fixed some time ago...

**Comment by dtcallcock** [comment]
My bad - clicked wrong link above.

- My comment about the Molex still stands though - shouldn't it have a dual footprint like on Stabilizer:
![image](https://user-images.githubusercontent.com/20587606/110149824-57b3d580-7d93-11eb-80a7-4928bf8ed893.png)

- Can we get an annotation about the OC setpoints and programmed regulator current limits?  Right now it looks like the positive rails are set to 600mA limit with 500mA OC threshold but the negative rail is 500mA/500mA.

- As the second positive rail is typically used for V_DD, would 1.8 and 2.5 options be more useful than 15 and 18?  It might be nice to trade the lower voltages for more current in this way too.  Could the limit be raised on this rail if the higher voltages aren't an option?  It looks like going above 800mA would involve paralleling a second LDO so that's perhaps not worth it.

- Why does the temperature sensor only shut off the negative rail?

- Can a 0R be added between the M8-4 shield and ground?  That would allow one to depopulate this if they wanted the shield connected at the load only.  Without being able to see the M8-4 part number, I cannot tell if the shield is likely to be isolated from the front panel.  If it isn't that probably rules this use case out.  However in that case, I think you still want the 0R as you need it to be able to isolate the front panel.

**Comment by gkasprow** [comment]
I implemented all suggestions

**Comment by dtcallcock** [comment]
Can you make a release with pdf if you have a min?

**Comment by gkasprow** [comment]
done
